Tag: V00-08-05 2013-11-12 Andy Salnikov - small improvement to ddl_* script
git-svn-id: https://pswww.slac.stanford.edu/svn-readonly/psdmrepo@7158 b967ad99-d558-0410-b138-e0f6c56caec7

diff --git a/psddl_pds2psana/trunk/app/ddl_pds2psana b/psddl_pds2psana/trunk/app/ddl_pds2psana
--- a/psddl_pds2psana/trunk/app/ddl_pds2psana
+++ b/psddl_pds2psana/trunk/app/ddl_pds2psana
@@ -2,8 +2,13 @@
 
 set -e
 
+if [ ! -d psddldata/data/ ]; then
+    echo "The psddldata/data directory was not found. Try doing 'addpkg psddldata' first."
+    exit 1
+fi
+
 # need all files from psddldata/data except for xtc.ddl.xml
-files="psddldata/data/[a-w]*.ddl.xml"
+files=`ls -1 psddldata/data/*.ddl.xml | grep -v xtc.ddl`
 
 for f in $files ; do 
     psddlc -b pds2psana -I data -E psddl_pds2psana/include -O psddl_pds2psana/src -i psddl_pds2psana -t psddl_pds2psana \
