- new 'lusvn export' command - new -x option for addpkg
git-svn-id: https://pswww.slac.stanford.edu/svn-readonly/psdmrepo@123 b967ad99-d558-0410-b138-e0f6c56caec7

diff --git a/bin/trunk/addpkg b/bin/trunk/addpkg
--- a/bin/trunk/addpkg
+++ b/bin/trunk/addpkg
@@ -15,6 +15,7 @@ Usage: `basename $0` [options] [package-name [package-tag]]
     -h          this message
     -d          debug (turn on -x shell option)
     -c          checkout from CVS [default is SVN]
+    -x          export instead of checkout
     -f {file|-} read the list of tags from file or standard input
 
   Checks out the packages from repository, the tag can be either a real 
@@ -47,7 +48,7 @@ find_tag() {
 checkout() {
 
   # checkout package
-  checkout_$4 "$1" `find_tag "$1" "$2" "$3"` || exit 2
+  checkout_$4 "$1" `find_tag "$1" "$2" "$3"` "$5" || exit 2
 
   # link or copy SConstruct file
   if [ "$1" = "SConsTools" ] ; then
@@ -61,10 +62,11 @@ checkout() {
 # usage: checkout_cvs package tag
 checkout_cvs() {
 
+  cmd="$3"
   if [ "$2" = "HEAD" ] ; then
-    cvs checkout "$1"
+    cvs "$cmd" "$1"
   else
-    cvs checkout -r "$2" "$1"
+    cvs "$cmd" -r "$2" "$1"
   fi
 
 }
@@ -76,10 +78,20 @@ checkout_svn() {
   test "$2" = "HEAD" || repo123="$SVNROOT/$1/tags/$2"
 
   # for existing packages use "switch"
-  if [ -d "$1" ] ; then
-    svn switch "$repo123" "$1"
+  if [ "$3" == "export" ] ; then
+  	# package should not exist yet
+  	if [ -d "$1" ] ; then
+      echo "Cannot export, package $1 already exist"
+      exit 2
+  	else
+      lusvn export "$1" "$2" "$1"
+    fi
   else
-    svn checkout "$repo123" "$1"
+    if [ -d "$1" ] ; then
+      svn switch "$repo123" "$1"
+    else
+      svn checkout "$repo123" "$1"
+    fi
   fi
   unset repo123
 }
@@ -88,13 +100,15 @@ checkout_svn() {
 mode="svn"
 link_scons="no"
 tag_file=""
+export="checkout"
 
 # get the options
-while getopts hdcf: c ; do
+while getopts hdcxf: c ; do
   case $c in
     h) usage ; exit 0 ;;
     d) set -x ;;
     c) mode="cvs" ;;
+    x) export="export" ;;
     f) tag_file="$OPTARG" ;;
     \?) usage ; exit 2 ;;
   esac
@@ -140,7 +154,7 @@ if [ "$tag_file" = '-' ] ; then
   # read tags from stdin, one line at a time
   while read pkg tag stuff ; do
     echo addpkg "$pkg" "$tag"
-    checkout "$pkg" "$tag" "$lusi_release" "$mode"
+    checkout "$pkg" "$tag" "$lusi_release" "$mode" "$export"
   done
 
 elif [ -n "$tag_file" ] ; then
@@ -148,7 +162,7 @@ elif [ -n "$tag_file" ] ; then
   # read tags from file, one line at a time
   while read pkg tag stuff ; do
     echo addpkg "$pkg" "$tag"
-    checkout "$pkg" "$tag" "$lusi_release" "$mode"
+    checkout "$pkg" "$tag" "$lusi_release" "$mode" "$export"
   done < "$tag_file"
 
 else
@@ -156,7 +170,7 @@ else
   # package name and optionally tag come from command line
   pkg=`echo $1 | cut -d/ -f1`
   tag="$2"
-  checkout "$pkg" "$tag" "$lusi_release" "$mode"
+  checkout "$pkg" "$tag" "$lusi_release" "$mode" "$export"
     
 fi
   
