Tag: V00-07-02 2013-11-12 Andy Salnikov - small improvement to ddl_* script
git-svn-id: https://pswww.slac.stanford.edu/svn-readonly/psdmrepo@7160 b967ad99-d558-0410-b138-e0f6c56caec7

diff --git a/psddl_hdf2psana/trunk/app/ddl_hdf2psana b/psddl_hdf2psana/trunk/app/ddl_hdf2psana
--- a/psddl_hdf2psana/trunk/app/ddl_hdf2psana
+++ b/psddl_hdf2psana/trunk/app/ddl_hdf2psana
@@ -2,7 +2,12 @@
 
 set -e
 
-packages=`ls -1 psddldata/data | cut -d. -f1 | grep -v xtc`
+if [ ! -d psddldata/data/ ]; then
+    echo "The psddldata/data directory was not found. Try doing 'addpkg psddldata' first."
+    exit 1
+fi
+
+packages=`(cd psddldata/data; ls -1 *.ddl.xml | cut -d. -f1 | grep -v xtc)`
 
 for pkg in $packages; do 
     f="psddldata/data/$pkg.ddl.xml" 
