Tag: V00-05-04 2013-11-12 Andy Salnikov - small improvement to ddl_* scripts
git-svn-id: https://pswww.slac.stanford.edu/svn-readonly/psdmrepo@7155 b967ad99-d558-0410-b138-e0f6c56caec7

diff --git a/psddl_psana/trunk/app/ddl_psana b/psddl_psana/trunk/app/ddl_psana
--- a/psddl_psana/trunk/app/ddl_psana
+++ b/psddl_psana/trunk/app/ddl_psana
@@ -2,6 +2,13 @@
 
 set -e
 
-for f in  psddldata/data/[a-w]*.ddl.xml ; do 
+if [ ! -d psddldata/data/ ]; then
+    echo "The psddldata/data directory was not found. Try doing 'addpkg psddldata' first."
+    exit 1
+fi
+
+files=`ls -1 psddldata/data/*.ddl.xml | grep -v xtc.ddl`
+
+for f in $files ; do 
     psddlc -b psana -I data -E psddl_psana/include -O psddl_psana/src -i psddl_psana -t Psana $f
 done
diff --git a/psddl_psana/trunk/app/ddl_psanadoc b/psddl_psana/trunk/app/ddl_psanadoc
--- a/psddl_psana/trunk/app/ddl_psanadoc
+++ b/psddl_psana/trunk/app/ddl_psanadoc
@@ -1,7 +1,16 @@
 #!/bin/sh
 
+set -e
+
+if [ ! -d psddldata/data/ ]; then
+    echo "The psddldata/data directory was not found. Try doing 'addpkg psddldata' first."
+    exit 1
+fi
+
 dir=${1:-psddl_psana/doc/html}
 mkdir -p "$dir"
 
+files=`ls -1 psddldata/data/*.ddl.xml | grep -v xtc.ddl`
+
 psddlc -b psana-doc -I data -O "$dir" -t Psana \
-    -B psana-inc:psddl_psana  psddldata/data/[a-w]*.ddl.xml
+    -B psana-inc:psddl_psana $files
